### PR TITLE
feat: add default timeouts to Guzzle Client

### PR DESCRIPTION
**Pull request by ankurk91**
Hi @mohammed-elhaouari,

Thanks for this awesome package.

It is recommended to have timeouts to HTTP clients, recently Laravel has added timeouts to their HTTP client too.

Read more:
* https://divinglaravel.com/always-set-a-timeout-for-guzzle-requests-inside-a-queued-job
* https://github.com/laravel/framework/pull/40466
* https://github.com/laravel/framework/pull/40187

Thanks.

### CODE REVIEW

**Review by mhdcodes — APPROVED** [review]

**Comment by ankurk91** [comment]
@mohammed-elhaouari 

GitHub actions are failing due to composer  version 2

**Comment by mhdcodes** [comment]
@ankurk91 I have merged #3 that should take care of allowing pest plugin. shouldn't this just run now ?

**Comment by ankurk91** [comment]
Yes, you can re-run the actions, which should take care of composer 2

**Comment by mhdcodes** [comment]
Apparently Github actions fails to update. it's still failing I'm gonna merge any way. Thanks for your great contribution @ankurk91

**Comment by ankurk91** [comment]
Thanks, it will pass after merging for sure.

Please tag a new version.

**Pull request merged**
